name: KGates
version: 1.5
main: me.erik.kgates.KGates
api-version: 1.21
author: ErikK81
commands:
  kgate:
    description: Manage the portals
    usage: /kgate
permissions:
  kgates.admin:
    description: Permite usar comandos administrativos do KGates
    default: op
